wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 200
batch_size:
  desc: null
  value: 8
image_size:
  desc: null
  value: 32
N_input_frames:
  desc: null
  value: 4
N_predictions:
  desc: null
  value: 4
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710044227.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.18
      5: 0.16.4
      8:
      - 5
      13: darwin-x86_64
